#! /bin/sh
if [[ "$(hostname)" == "archdesktop" ]]; then
        sh ~/.scripts/archdesktop-monitors.sh &

        bspc monitor DP-0 -d 1 2 3 4
        bspc monitor DVI-D-0 -d 5 6 7
        bspc monitor DP-3 -d 8 9 10

        bspc config border_width         0
        bspc config window_gap           16

        bspc config split_ratio          0.52
        bspc config borderless_monocle   true
        bspc config gapless_monocle      true

        bspc rule -a "TeamSpeak 3" desktop=5
        bspc rule -a "discord" desktop=5
        bspc rule -a "Ferdi" desktop=6
        bspc rule -a "obs" desktop=10 
else
        bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

        bspc config border_width         0
        bspc config window_gap           16

        bspc config split_ratio          0.52
        bspc config borderless_monocle   true
        bspc config gapless_monocle      true

        bspc config remove_disabled_monitors true
        bspc config remove_unplugged_monitors true
fi

xsetroot -cursor_name left_ptr & # X cursor fix
feh --bg-fill ~/images/wallpaper.jpg & # Wallpaper
pidof sxhkd > /dev/null || { sxhkd > /dev/null 2>&1 & } & # Keyboard shortcuts

dunst & # Notifications
redshift-gtk &
nm-applet &
dropbox &
flatpak run com.discordapp.Discord &
discord &
steam -silent &
spotify &
insync start &
/usr/bin/lxqt-policykit-agent &

~/.config/polybar/launch.sh "~/.config/polybar/config.ini" & # Status bar

